# Generated by Django 3.1.5 on 2021-02-16 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceplan',
            name='drill',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='post_type',
            field=models.CharField(choices=[('BLG', 'Blog'), ('DRL', 'Drill'), ('PRP', 'Practice Plan')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Drill',
        ),
        migrations.DeleteModel(
            name='PracticePlan',
        ),
    ]
