# Generated by Django 3.1.5 on 2021-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210216_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_categories',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MED', 'Medical'), ('FIT', 'Fitness'), ('FUT', 'Futball'), ('HKY', 'Hockey'), ('BSK', 'Basketball')], default='Medical', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('BLG', 'Blog'), ('DRL', 'Drill'), ('PRP', 'Practice Plan')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PostType',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
