# Generated by Django 3.1.5 on 2021-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210216_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('post_type', 'category', 'sub_categories', 'title', 'description', 'user', 'image', 'created_at')},
        ),
        migrations.AddField(
            model_name='post',
            name='sub_categories',
            field=models.CharField(choices=[('ALL', 'All'), ('NUT', 'Nutrition'), ('CNC', 'Concussion'), ('IRH', 'Injury Rehabilitation'), ('SRB', 'Surgical Rehabilitation'), ('IPV', 'Injury Prevention'), ('MTH', 'Mental Health')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/post/<post_type>/<category>/'),
        ),
    ]
