# Generated by Django 3.1.5 on 2021-02-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210217_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MED', 'Medical'), ('FIT', 'Fitness'), ('FUT', 'Soccer'), ('HKY', 'Hockey'), ('BSK', 'Basketball')], default='Medical', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_categories',
            field=models.CharField(choices=[('ALL', 'All'), ('NUT', 'Nutrition'), ('CNC', 'Concussion'), ('IRH', 'Injury Rehabilitation'), ('SRB', 'Surgical Rehabilitation'), ('IPV', 'Injury Prevention'), ('MTH', 'Mental Health')], default='All', max_length=50),
        ),
    ]
