# Generated by Django 3.1.5 on 2021-03-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210222_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MED', 'Medical'), ('FIT', 'Fitness'), ('FUT', 'Soccer'), ('HKY', 'Hockey'), ('BSK', 'Basketball')], default='All', max_length=20),
        ),
    ]
