# Generated by Django 3.1.5 on 2021-04-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210409_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at', 'post_type', 'category', 'sub_categories', 'title', 'description', 'user', 'image')},
        ),
    ]
