# Generated by Django 3.1.5 on 2021-04-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210412_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MED', 'Medical'), ('FIT', 'Fitness'), ('FUT', 'Soccer'), ('HKY', 'Hockey'), ('BSK', 'Basketball'), ('AFB', 'Football'), ('RUG', 'Rugby')], default='All', max_length=20),
        ),
    ]
